//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public interface AirConditionerPrx extends SmartDevicePrx
{
    default Temperature getCurrentTemperature()
        throws DeviceNotInOperationalState
    {
        return getCurrentTemperature(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Temperature getCurrentTemperature(java.util.Map<String, String> context)
        throws DeviceNotInOperationalState
    {
        try
        {
            return _iceI_getCurrentTemperatureAsync(context, true).waitForResponseOrUserEx();
        }
        catch(DeviceNotInOperationalState ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Temperature> getCurrentTemperatureAsync()
    {
        return _iceI_getCurrentTemperatureAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Temperature> getCurrentTemperatureAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentTemperatureAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Temperature> _iceI_getCurrentTemperatureAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Temperature> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurrentTemperature", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getCurrentTemperature);
        f.invoke(true, context, null, null, istr -> {
                     Temperature ret;
                     ret = Temperature.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getCurrentTemperature =
    {
        DeviceNotInOperationalState.class
    };

    default Temperature getTargetTemperature()
        throws DeviceNotInOperationalState
    {
        return getTargetTemperature(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Temperature getTargetTemperature(java.util.Map<String, String> context)
        throws DeviceNotInOperationalState
    {
        try
        {
            return _iceI_getTargetTemperatureAsync(context, true).waitForResponseOrUserEx();
        }
        catch(DeviceNotInOperationalState ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Temperature> getTargetTemperatureAsync()
    {
        return _iceI_getTargetTemperatureAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Temperature> getTargetTemperatureAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTargetTemperatureAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Temperature> _iceI_getTargetTemperatureAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Temperature> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTargetTemperature", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getTargetTemperature);
        f.invoke(true, context, null, null, istr -> {
                     Temperature ret;
                     ret = Temperature.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getTargetTemperature =
    {
        DeviceNotInOperationalState.class
    };

    default double getHumidity()
        throws DeviceNotInOperationalState
    {
        return getHumidity(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double getHumidity(java.util.Map<String, String> context)
        throws DeviceNotInOperationalState
    {
        try
        {
            return _iceI_getHumidityAsync(context, true).waitForResponseOrUserEx();
        }
        catch(DeviceNotInOperationalState ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getHumidityAsync()
    {
        return _iceI_getHumidityAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getHumidityAsync(java.util.Map<String, String> context)
    {
        return _iceI_getHumidityAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_getHumidityAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getHumidity", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getHumidity);
        f.invoke(true, context, null, null, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getHumidity =
    {
        DeviceNotInOperationalState.class
    };

    default TemperatureUnit getTemperatureUnit()
        throws NoPowerError
    {
        return getTemperatureUnit(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default TemperatureUnit getTemperatureUnit(java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            return _iceI_getTemperatureUnitAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<TemperatureUnit> getTemperatureUnitAsync()
    {
        return _iceI_getTemperatureUnitAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<TemperatureUnit> getTemperatureUnitAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTemperatureUnitAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<TemperatureUnit> _iceI_getTemperatureUnitAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<TemperatureUnit> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTemperatureUnit", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getTemperatureUnit);
        f.invoke(true, context, null, null, istr -> {
                     TemperatureUnit ret;
                     ret = TemperatureUnit.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getTemperatureUnit =
    {
        NoPowerError.class
    };

    default void setTemperatureUnit(TemperatureUnit unit)
        throws NoPowerError
    {
        setTemperatureUnit(unit, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setTemperatureUnit(TemperatureUnit unit, java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            _iceI_setTemperatureUnitAsync(unit, context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setTemperatureUnitAsync(TemperatureUnit unit)
    {
        return _iceI_setTemperatureUnitAsync(unit, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setTemperatureUnitAsync(TemperatureUnit unit, java.util.Map<String, String> context)
    {
        return _iceI_setTemperatureUnitAsync(unit, context, false);
    }

    /**
     * @hidden
     * @param iceP_unit -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setTemperatureUnitAsync(TemperatureUnit iceP_unit, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setTemperatureUnit", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setTemperatureUnit);
        f.invoke(true, context, null, ostr -> {
                     TemperatureUnit.ice_write(ostr, iceP_unit);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setTemperatureUnit =
    {
        NoPowerError.class
    };

    default ACSettings getSettings()
        throws NoPowerError
    {
        return getSettings(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ACSettings getSettings(java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            return _iceI_getSettingsAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ACSettings> getSettingsAsync()
    {
        return _iceI_getSettingsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ACSettings> getSettingsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getSettingsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ACSettings> _iceI_getSettingsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ACSettings> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSettings", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getSettings);
        f.invoke(true, context, null, null, istr -> {
                     ACSettings ret;
                     ret = ACSettings.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getSettings =
    {
        NoPowerError.class
    };

    default void setSettings(ACSettings settings)
        throws DeviceError,
               NoPowerError
    {
        setSettings(settings, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setSettings(ACSettings settings, java.util.Map<String, String> context)
        throws DeviceError,
               NoPowerError
    {
        try
        {
            _iceI_setSettingsAsync(settings, context, true).waitForResponseOrUserEx();
        }
        catch(DeviceError ex)
        {
            throw ex;
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setSettingsAsync(ACSettings settings)
    {
        return _iceI_setSettingsAsync(settings, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setSettingsAsync(ACSettings settings, java.util.Map<String, String> context)
    {
        return _iceI_setSettingsAsync(settings, context, false);
    }

    /**
     * @hidden
     * @param iceP_settings -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setSettingsAsync(ACSettings iceP_settings, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setSettings", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setSettings);
        f.invoke(true, context, null, ostr -> {
                     ACSettings.ice_write(ostr, iceP_settings);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setSettings =
    {
        DeviceError.class,
        NoPowerError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirConditionerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirConditionerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirConditionerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AirConditionerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AirConditionerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AirConditionerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AirConditionerPrx.class, _AirConditionerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AirConditionerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AirConditionerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AirConditionerPrx ice_adapterId(String newAdapterId)
    {
        return (AirConditionerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AirConditionerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AirConditionerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AirConditionerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AirConditionerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AirConditionerPrx ice_invocationTimeout(int newTimeout)
    {
        return (AirConditionerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AirConditionerPrx ice_connectionCached(boolean newCache)
    {
        return (AirConditionerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AirConditionerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AirConditionerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AirConditionerPrx ice_secure(boolean b)
    {
        return (AirConditionerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AirConditionerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AirConditionerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AirConditionerPrx ice_preferSecure(boolean b)
    {
        return (AirConditionerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AirConditionerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AirConditionerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AirConditionerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AirConditionerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AirConditionerPrx ice_collocationOptimized(boolean b)
    {
        return (AirConditionerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AirConditionerPrx ice_twoway()
    {
        return (AirConditionerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AirConditionerPrx ice_oneway()
    {
        return (AirConditionerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AirConditionerPrx ice_batchOneway()
    {
        return (AirConditionerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AirConditionerPrx ice_datagram()
    {
        return (AirConditionerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AirConditionerPrx ice_batchDatagram()
    {
        return (AirConditionerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AirConditionerPrx ice_compress(boolean co)
    {
        return (AirConditionerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AirConditionerPrx ice_timeout(int t)
    {
        return (AirConditionerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AirConditionerPrx ice_connectionId(String connectionId)
    {
        return (AirConditionerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AirConditionerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AirConditionerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHomeIce::AirConditioner";
    }
}
