//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

/**
 * Helper class for marshaling/unmarshaling CameraSettingsList.
 **/
public final class CameraSettingsListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, CameraSettings[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                CameraSettings.ice_write(ostr, v[i0]);
            }
        }
    }

    public static CameraSettings[] read(com.zeroc.Ice.InputStream istr)
    {
        final CameraSettings[] v;
        final int len0 = istr.readAndCheckSeqSize(12);
        v = new CameraSettings[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = CameraSettings.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CameraSettings[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, CameraSettings[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 12 + 5 : optSize * 12 + 1);
            CameraSettingsListHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<CameraSettings[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            CameraSettings[] v;
            v = CameraSettingsListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
