//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public class DeviceNotInOperationalState extends com.zeroc.Ice.UserException
{
    public DeviceNotInOperationalState()
    {
    }

    public DeviceNotInOperationalState(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::SmartHomeIce::DeviceNotInOperationalState";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHomeIce::DeviceNotInOperationalState", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -2101761285L;
}
