//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public interface IndoorCamera extends Camera
{
    boolean isMotionDetectionModeOn(com.zeroc.Ice.Current current)
        throws NoPowerError;

    void setMotionDetectionMode(boolean mode, com.zeroc.Ice.Current current)
        throws NoPowerError;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::SmartHomeIce::Camera",
        "::SmartHomeIce::IndoorCamera",
        "::SmartHomeIce::SmartDevice"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::SmartHomeIce::IndoorCamera";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isMotionDetectionModeOn(IndoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        boolean ret = obj.isMotionDetectionModeOn(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setMotionDetectionMode(IndoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        boolean iceP_mode;
        iceP_mode = istr.readBool();
        inS.endReadParams();
        obj.setMotionDetectionMode(iceP_mode, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getCurrentSettings",
        "getPowerState",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "isMotionDetectionModeOn",
        "isRecording",
        "move",
        "setCurrentSettings",
        "setMotionDetectionMode",
        "setPowerState",
        "startRecording",
        "stopRecording"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return Camera._iceD_getCurrentSettings(this, in, current);
            }
            case 1:
            {
                return SmartDevice._iceD_getPowerState(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_isMotionDetectionModeOn(this, in, current);
            }
            case 7:
            {
                return Camera._iceD_isRecording(this, in, current);
            }
            case 8:
            {
                return Camera._iceD_move(this, in, current);
            }
            case 9:
            {
                return Camera._iceD_setCurrentSettings(this, in, current);
            }
            case 10:
            {
                return _iceD_setMotionDetectionMode(this, in, current);
            }
            case 11:
            {
                return SmartDevice._iceD_setPowerState(this, in, current);
            }
            case 12:
            {
                return Camera._iceD_startRecording(this, in, current);
            }
            case 13:
            {
                return Camera._iceD_stopRecording(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
