//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public enum moveCommand implements java.io.Serializable
{
    PanLeft(0),
    PanRight(1),
    TiltUp(2),
    TiltDown(3),
    ZoomIn(4),
    ZoomOut(5);

    public int value()
    {
        return _value;
    }

    public static moveCommand valueOf(int v)
    {
        switch(v)
        {
        case 0:
            return PanLeft;
        case 1:
            return PanRight;
        case 2:
            return TiltUp;
        case 3:
            return TiltDown;
        case 4:
            return ZoomIn;
        case 5:
            return ZoomOut;
        }
        return null;
    }

    private moveCommand(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 5);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, moveCommand v)
    {
        if(v == null)
        {
            ostr.writeEnum(SmartHomeIce.moveCommand.PanLeft.value(), 5);
        }
        else
        {
            ostr.writeEnum(v.value(), 5);
        }
    }

    public static moveCommand ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(5);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<moveCommand> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, moveCommand v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<moveCommand> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static moveCommand validate(int v)
    {
        final moveCommand e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
