//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public interface OutdoorCamera extends Camera
{
    boolean isNightVisionModeOn(com.zeroc.Ice.Current current)
        throws NoPowerError;

    void setNightVisionMode(boolean mode, com.zeroc.Ice.Current current)
        throws NoPowerError;

    boolean isPresetMovementModeOn(com.zeroc.Ice.Current current)
        throws NoPowerError;

    void setPresetMovementMode(boolean mode, com.zeroc.Ice.Current current)
        throws NoPowerError;

    CameraSettings[] getPresetSettingsList(com.zeroc.Ice.Current current)
        throws NoPowerError;

    void setPresetSettingsList(CameraSettings[] settingsList, com.zeroc.Ice.Current current)
        throws DeviceError,
               NoPowerError;

    void goToNextPreset(com.zeroc.Ice.Current current)
        throws DeviceError,
               DeviceNotInOperationalState;

    void goToPreviousPreset(com.zeroc.Ice.Current current)
        throws DeviceError,
               DeviceNotInOperationalState;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::SmartHomeIce::Camera",
        "::SmartHomeIce::OutdoorCamera",
        "::SmartHomeIce::SmartDevice"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::SmartHomeIce::OutdoorCamera";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isNightVisionModeOn(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        boolean ret = obj.isNightVisionModeOn(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setNightVisionMode(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        boolean iceP_mode;
        iceP_mode = istr.readBool();
        inS.endReadParams();
        obj.setNightVisionMode(iceP_mode, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_isPresetMovementModeOn(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        boolean ret = obj.isPresetMovementModeOn(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setPresetMovementMode(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        boolean iceP_mode;
        iceP_mode = istr.readBool();
        inS.endReadParams();
        obj.setPresetMovementMode(iceP_mode, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPresetSettingsList(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        CameraSettings[] ret = obj.getPresetSettingsList(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        CameraSettingsListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setPresetSettingsList(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        CameraSettings[] iceP_settingsList;
        iceP_settingsList = CameraSettingsListHelper.read(istr);
        inS.endReadParams();
        obj.setPresetSettingsList(iceP_settingsList, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_goToNextPreset(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        obj.goToNextPreset(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_goToPreviousPreset(OutdoorCamera obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        obj.goToPreviousPreset(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getCurrentSettings",
        "getPowerState",
        "getPresetSettingsList",
        "goToNextPreset",
        "goToPreviousPreset",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "isNightVisionModeOn",
        "isPresetMovementModeOn",
        "isRecording",
        "move",
        "setCurrentSettings",
        "setNightVisionMode",
        "setPowerState",
        "setPresetMovementMode",
        "setPresetSettingsList",
        "startRecording",
        "stopRecording"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return Camera._iceD_getCurrentSettings(this, in, current);
            }
            case 1:
            {
                return SmartDevice._iceD_getPowerState(this, in, current);
            }
            case 2:
            {
                return _iceD_getPresetSettingsList(this, in, current);
            }
            case 3:
            {
                return _iceD_goToNextPreset(this, in, current);
            }
            case 4:
            {
                return _iceD_goToPreviousPreset(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 9:
            {
                return _iceD_isNightVisionModeOn(this, in, current);
            }
            case 10:
            {
                return _iceD_isPresetMovementModeOn(this, in, current);
            }
            case 11:
            {
                return Camera._iceD_isRecording(this, in, current);
            }
            case 12:
            {
                return Camera._iceD_move(this, in, current);
            }
            case 13:
            {
                return Camera._iceD_setCurrentSettings(this, in, current);
            }
            case 14:
            {
                return _iceD_setNightVisionMode(this, in, current);
            }
            case 15:
            {
                return SmartDevice._iceD_setPowerState(this, in, current);
            }
            case 16:
            {
                return _iceD_setPresetMovementMode(this, in, current);
            }
            case 17:
            {
                return _iceD_setPresetSettingsList(this, in, current);
            }
            case 18:
            {
                return Camera._iceD_startRecording(this, in, current);
            }
            case 19:
            {
                return Camera._iceD_stopRecording(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
