//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHomeIce;

public interface OutdoorCameraPrx extends CameraPrx
{
    default boolean isNightVisionModeOn()
        throws NoPowerError
    {
        return isNightVisionModeOn(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isNightVisionModeOn(java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            return _iceI_isNightVisionModeOnAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isNightVisionModeOnAsync()
    {
        return _iceI_isNightVisionModeOnAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isNightVisionModeOnAsync(java.util.Map<String, String> context)
    {
        return _iceI_isNightVisionModeOnAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isNightVisionModeOnAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isNightVisionModeOn", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_isNightVisionModeOn);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_isNightVisionModeOn =
    {
        NoPowerError.class
    };

    default void setNightVisionMode(boolean mode)
        throws NoPowerError
    {
        setNightVisionMode(mode, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setNightVisionMode(boolean mode, java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            _iceI_setNightVisionModeAsync(mode, context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setNightVisionModeAsync(boolean mode)
    {
        return _iceI_setNightVisionModeAsync(mode, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setNightVisionModeAsync(boolean mode, java.util.Map<String, String> context)
    {
        return _iceI_setNightVisionModeAsync(mode, context, false);
    }

    /**
     * @hidden
     * @param iceP_mode -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setNightVisionModeAsync(boolean iceP_mode, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setNightVisionMode", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setNightVisionMode);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeBool(iceP_mode);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setNightVisionMode =
    {
        NoPowerError.class
    };

    default boolean isPresetMovementModeOn()
        throws NoPowerError
    {
        return isPresetMovementModeOn(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean isPresetMovementModeOn(java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            return _iceI_isPresetMovementModeOnAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isPresetMovementModeOnAsync()
    {
        return _iceI_isPresetMovementModeOnAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> isPresetMovementModeOnAsync(java.util.Map<String, String> context)
    {
        return _iceI_isPresetMovementModeOnAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_isPresetMovementModeOnAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "isPresetMovementModeOn", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_isPresetMovementModeOn);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_isPresetMovementModeOn =
    {
        NoPowerError.class
    };

    default void setPresetMovementMode(boolean mode)
        throws NoPowerError
    {
        setPresetMovementMode(mode, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setPresetMovementMode(boolean mode, java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            _iceI_setPresetMovementModeAsync(mode, context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setPresetMovementModeAsync(boolean mode)
    {
        return _iceI_setPresetMovementModeAsync(mode, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setPresetMovementModeAsync(boolean mode, java.util.Map<String, String> context)
    {
        return _iceI_setPresetMovementModeAsync(mode, context, false);
    }

    /**
     * @hidden
     * @param iceP_mode -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setPresetMovementModeAsync(boolean iceP_mode, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setPresetMovementMode", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setPresetMovementMode);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeBool(iceP_mode);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setPresetMovementMode =
    {
        NoPowerError.class
    };

    default CameraSettings[] getPresetSettingsList()
        throws NoPowerError
    {
        return getPresetSettingsList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CameraSettings[] getPresetSettingsList(java.util.Map<String, String> context)
        throws NoPowerError
    {
        try
        {
            return _iceI_getPresetSettingsListAsync(context, true).waitForResponseOrUserEx();
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<CameraSettings[]> getPresetSettingsListAsync()
    {
        return _iceI_getPresetSettingsListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CameraSettings[]> getPresetSettingsListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getPresetSettingsListAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CameraSettings[]> _iceI_getPresetSettingsListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CameraSettings[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPresetSettingsList", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getPresetSettingsList);
        f.invoke(true, context, null, null, istr -> {
                     CameraSettings[] ret;
                     ret = CameraSettingsListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getPresetSettingsList =
    {
        NoPowerError.class
    };

    default void setPresetSettingsList(CameraSettings[] settingsList)
        throws DeviceError,
               NoPowerError
    {
        setPresetSettingsList(settingsList, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setPresetSettingsList(CameraSettings[] settingsList, java.util.Map<String, String> context)
        throws DeviceError,
               NoPowerError
    {
        try
        {
            _iceI_setPresetSettingsListAsync(settingsList, context, true).waitForResponseOrUserEx();
        }
        catch(DeviceError ex)
        {
            throw ex;
        }
        catch(NoPowerError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> setPresetSettingsListAsync(CameraSettings[] settingsList)
    {
        return _iceI_setPresetSettingsListAsync(settingsList, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setPresetSettingsListAsync(CameraSettings[] settingsList, java.util.Map<String, String> context)
    {
        return _iceI_setPresetSettingsListAsync(settingsList, context, false);
    }

    /**
     * @hidden
     * @param iceP_settingsList -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setPresetSettingsListAsync(CameraSettings[] iceP_settingsList, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setPresetSettingsList", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setPresetSettingsList);
        f.invoke(true, context, null, ostr -> {
                     CameraSettingsListHelper.write(ostr, iceP_settingsList);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setPresetSettingsList =
    {
        DeviceError.class,
        NoPowerError.class
    };

    default void goToNextPreset()
        throws DeviceError,
               DeviceNotInOperationalState
    {
        goToNextPreset(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void goToNextPreset(java.util.Map<String, String> context)
        throws DeviceError,
               DeviceNotInOperationalState
    {
        try
        {
            _iceI_goToNextPresetAsync(context, true).waitForResponseOrUserEx();
        }
        catch(DeviceError ex)
        {
            throw ex;
        }
        catch(DeviceNotInOperationalState ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> goToNextPresetAsync()
    {
        return _iceI_goToNextPresetAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> goToNextPresetAsync(java.util.Map<String, String> context)
    {
        return _iceI_goToNextPresetAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_goToNextPresetAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "goToNextPreset", null, sync, _iceE_goToNextPreset);
        f.invoke(true, context, null, null, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_goToNextPreset =
    {
        DeviceError.class,
        DeviceNotInOperationalState.class
    };

    default void goToPreviousPreset()
        throws DeviceError,
               DeviceNotInOperationalState
    {
        goToPreviousPreset(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void goToPreviousPreset(java.util.Map<String, String> context)
        throws DeviceError,
               DeviceNotInOperationalState
    {
        try
        {
            _iceI_goToPreviousPresetAsync(context, true).waitForResponseOrUserEx();
        }
        catch(DeviceError ex)
        {
            throw ex;
        }
        catch(DeviceNotInOperationalState ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> goToPreviousPresetAsync()
    {
        return _iceI_goToPreviousPresetAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> goToPreviousPresetAsync(java.util.Map<String, String> context)
    {
        return _iceI_goToPreviousPresetAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_goToPreviousPresetAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "goToPreviousPreset", null, sync, _iceE_goToPreviousPreset);
        f.invoke(true, context, null, null, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_goToPreviousPreset =
    {
        DeviceError.class,
        DeviceNotInOperationalState.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OutdoorCameraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OutdoorCameraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OutdoorCameraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OutdoorCameraPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static OutdoorCameraPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static OutdoorCameraPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, OutdoorCameraPrx.class, _OutdoorCameraPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default OutdoorCameraPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (OutdoorCameraPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default OutdoorCameraPrx ice_adapterId(String newAdapterId)
    {
        return (OutdoorCameraPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default OutdoorCameraPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (OutdoorCameraPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default OutdoorCameraPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (OutdoorCameraPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default OutdoorCameraPrx ice_invocationTimeout(int newTimeout)
    {
        return (OutdoorCameraPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default OutdoorCameraPrx ice_connectionCached(boolean newCache)
    {
        return (OutdoorCameraPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default OutdoorCameraPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (OutdoorCameraPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OutdoorCameraPrx ice_secure(boolean b)
    {
        return (OutdoorCameraPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default OutdoorCameraPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (OutdoorCameraPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OutdoorCameraPrx ice_preferSecure(boolean b)
    {
        return (OutdoorCameraPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default OutdoorCameraPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (OutdoorCameraPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default OutdoorCameraPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (OutdoorCameraPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default OutdoorCameraPrx ice_collocationOptimized(boolean b)
    {
        return (OutdoorCameraPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default OutdoorCameraPrx ice_twoway()
    {
        return (OutdoorCameraPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default OutdoorCameraPrx ice_oneway()
    {
        return (OutdoorCameraPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default OutdoorCameraPrx ice_batchOneway()
    {
        return (OutdoorCameraPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default OutdoorCameraPrx ice_datagram()
    {
        return (OutdoorCameraPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default OutdoorCameraPrx ice_batchDatagram()
    {
        return (OutdoorCameraPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default OutdoorCameraPrx ice_compress(boolean co)
    {
        return (OutdoorCameraPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default OutdoorCameraPrx ice_timeout(int t)
    {
        return (OutdoorCameraPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default OutdoorCameraPrx ice_connectionId(String connectionId)
    {
        return (OutdoorCameraPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default OutdoorCameraPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (OutdoorCameraPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHomeIce::OutdoorCamera";
    }
}
